services:

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    depends_on:
      - server
    
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    depends_on:
      bdd :
        condition: service_healthy
    environment:
      DB_HOST: bdd
      DB_NAME: docker_bdd
      DB_USER: docker_user
      DB_PASSWORD: docker_password
    ports:
      - 3310:3310
  bdd:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: docker_bdd
      MYSQL_USER: docker_user
      MYSQL_PASSWORD: docker_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "docker_user", "--password=docker_password"]
      interval: 10s
      timeout: 5s
      retries: 5